// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OurBeauty.API.Data;

#nullable disable

namespace OurBeauty.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250701003650_SeedProductsTable")]
    partial class SeedProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A vibrant and long-lasting lipstick that provides full coverage and a comfortable feel.",
                            ImageUrl = "https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg",
                            Name = "Luxury Lipstick",
                            Price = 350m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A lightweight foundation that offers a natural, flawless finish for all skin types.",
                            ImageUrl = "https://images.pexels.com/photos/3373723/pexels-photo-3373723.jpeg",
                            Name = "Foundation Cream",
                            Price = 550m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A versatile palette with a mix of matte and shimmer shades to create endless eye looks.",
                            ImageUrl = "https://images.pexels.com/photos/3373739/pexels-photo-3373739.jpeg",
                            Name = "Eyeshadow Palette",
                            Price = 750m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A powerful serum packed with vitamins to rejuvenate and hydrate your skin.",
                            ImageUrl = "https://images.pexels.com/photos/5863397/pexels-photo-5863397.jpeg",
                            Name = "Skincare Serum",
                            Price = 900m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
